
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.test
{
/// <summary>
/// 这是一个矩形
/// </summary>
public sealed partial class Rectangle : Shape
{
    public Rectangle(ByteBuf _buf)  : base(_buf) 
    {
        Width = _buf.ReadFloat();
        Height = _buf.ReadFloat();
    }

    public static Rectangle DeserializeRectangle(ByteBuf _buf)
    {
        return new test.Rectangle(_buf);
    }

    /// <summary>
    /// 宽度
    /// </summary>
    public readonly float Width;
    /// <summary>
    /// 高度
    /// </summary>
    public readonly float Height;
   
    public const int __ID__ = -31893773;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "}";
    }
}

}
